# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release CI-CD

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build ahgora-login
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: intall dependencies
        run: npm install
        working-directory: app

      - name: build app react
        run: npm run build
        working-directory: app

      - name: install neutralinojs
        run: npm install -g @neutralinojs/neu

      - name: build neutralino project
        run: neu update && neu build

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: ahgora-login
          path: dist